export const PROBLEM_BASE_URL = 'https://www.jhipster.tech/problem';
export const EMAIL_ALREADY_USED_TYPE = PROBLEM_BASE_URL + '/email-already-used';
export const LOGIN_ALREADY_USED_TYPE = PROBLEM_BASE_URL + '/login-already-used';
export const EMAIL_NOT_FOUND_TYPE = PROBLEM_BASE_URL + '/email-not-found';
export const INVALID_PASSWORD_TYPE = PROBLEM_BASE_URL + '/invalid-password';
export const CONSTRAINT_VIOLATION_TYPE = PROBLEM_BASE_URL + '/constraint-violation';
export const YEAR_ERROR = PROBLEM_BASE_URL + '/year-error';
export const IMAGE_ERROR = PROBLEM_BASE_URL + '/image-error';
export const BANDNAME_ERROR = PROBLEM_BASE_URL + '/name-error';
